pre_init:
  - wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.9.5-a1c09b93.tar.gz
  - tar -xf geth-linux-amd64-1.9.5-a1c09b93.tar.gz
  - cp geth-linux-amd64-1.9.5-a1c09b93/geth /usr/bin
  - rm -rf geth-linux-amd64-1.9.5-a1c09b93 geth-linux-amd64-1.9.5-a1c09b93.tar.gz
  - >
    echo '{
      "config": {
        "chainId": 15,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
      },
      "difficulty": "0x400",
      "gasLimit": "0x999999999",
      "alloc": {}
    }' > init.json
  - echo password > password
  - :> accounts.txt

node_init:
  # pre-init many accounts
  - for j in $(seq 1 1 10); do geth --datadir=./.eth/1 account new --password=password 2> /dev/null | sed -nr '/0x/s/(.*)0x(.*)/\2/p' >> accounts.txt && tail -n 1 accounts.txt; done

post_init:
  - >
    sed "/alloc/s/{}/{$(echo $(sed -r 's/(.*)/"\1": \{ "balance": "0x999999999999999999999999999" \}/g; $!s/$/,/' accounts.txt))}/g" init.json > init_new.json
  - for i in $(seq 0 1 $(({%n}-1))); do geth --datadir=./.eth/$i init init_new.json ; done;
  - for i in $(seq 0 1 $(({%n}-1))); do geth --datadir=./.eth/$i --port 500$i 2> /dev/null & done
  - sleep 3

wallet_init:
  - sed -n '$p' accounts.txt && sed -in '$d' accounts.txt

transaction:
  - >
    geth --exec 'personal.sendTransaction({from: "{%from}", to: "{%to}", value: "{%sum}"}, "password");' attach ipc:.eth/1/geth.ipc 2> /dev/null

cleanup:
  - rm -rf ./.eth init.json init_new.json accounts.txt password
